# Generated by Django 4.2.3 on 2023-07-04 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='realese_year',
            new_name='realease_year',
        ),
    ]
