# Generated by Django 4.2.3 on 2023-07-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_realese_year_album_realease_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='realease_year',
            new_name='release_year',
        ),
    ]
