# Generated by Django 4.2.3 on 2023-07-07 13:29

from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_rename_realease_year_album_release_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=music.models.image_upload_path)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='music.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='tag',
            field=models.ManyToManyField(blank=True, to='music.tag'),
        ),
    ]
