# Generated by Django 4.2 on 2023-05-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tag_alter_post_mood_comment_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.CharField(choices=[('bad', '별로에요'), ('so-so', '아무 생각이 없어요'), ('good', '좋아요')], default='so-so', max_length=5),
        ),
    ]
