# Generated by Django 4.2 on 2023-05-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_post_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='comments', to='main.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.CharField(choices=[('bad', '별로에요'), ('good', '좋아요'), ('so-so', '아무 생각이 없어요')], default='so-so', max_length=5),
        ),
    ]
