# Generated by Django 4.2 on 2023-06-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_post_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.CharField(choices=[('good', '좋아요'), ('so-so', '아무 생각이 없어요'), ('bad', '별로에요')], default='so-so', max_length=5),
        ),
    ]
