# Generated by Django 4.2.3 on 2023-07-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_post_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.CharField(choices=[('bad', '별로에요'), ('so-so', '아무 생각이 없어요'), ('good', '좋아요')], default='so-so', max_length=5),
        ),
    ]
