# Generated by Django 4.2 on 2023-04-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('mood', models.CharField(choices=[('bad', '별로에요'), ('good', '좋아요'), ('so-so', '아무 생각이 없어요')], max_length=100)),
                ('tmi', models.TextField()),
            ],
        ),
    ]
